version: '3.8'

include:
  - path: "app/docker-compose.yml"
    env_file: "app/.env"
  - path: "dwh/docker-compose.yml"
    env_file: "dwh/.env"
  - path: "airflow/docker-compose.yml"
    env_file: "airflow/.env"

networks:
  md-course-network:
    driver: bridge
