services:
  crypto-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - crypto-app-mongodb

  crypto-app-mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME:-admin}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD:-admin}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE:-crypto_data}"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./volumes/mongodb/data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
